[package]
name = "iotop"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.29"
ratatui = { version = "0.25", default-features = false, features = ["crossterm"] }
procfs = "0.16"
anyhow = "1.0"